export const IPC_CHANNELS = {
  assistantAsk: 'orbit:assistant:ask',
  assistantCancel: 'orbit:assistant:cancel',
  assistantProgress: 'orbit:assistant:progress',
  wakeWordStart: 'orbit:wake-word:start',
  wakeWordStop: 'orbit:wake-word:stop',
  wakeWordPause: 'orbit:wake-word:pause',
  wakeWordResume: 'orbit:wake-word:resume',
  wakeWordTestStart: 'orbit:wake-word:test-start',
  wakeWordTestCancel: 'orbit:wake-word:test-cancel',
  wakeWordAudioChunk: 'orbit:wake-word:audio-chunk',
  wakeWordEvent: 'orbit:wake-word:event',
  microphoneTestTranscribe: 'orbit:microphone-test:transcribe',
  microphoneTestCancel: 'orbit:microphone-test:cancel',
  speechSynthesize: 'orbit:speech:synthesize',
  speechCancel: 'orbit:speech:cancel',
  speechEvent: 'orbit:speech:event',
  ollamaHealth: 'orbit:ollama:health',
  settingsGet: 'orbit:settings:get',
  settingsUpdate: 'orbit:settings:update',
  securityPinStatus: 'orbit:security-pin:status',
  securityPinCreate: 'orbit:security-pin:create',
  securityPinChange: 'orbit:security-pin:change',
  actionExecute: 'orbit:action:execute',
  actionConfirm: 'orbit:action:confirm'
} as const
